spring.application.name=UserAuthService_June2025

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/userauthservice_june2025
spring.datasource.username=root
spring.datasource.password=pruthvi@1212
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true